name: personal file

on:
  push:
    branches: [main]

jobs:
  personal_details:
    runs-on: ubuntu-latest

    steps:
      - name: name of the username
        run: echo "Hello to $USER"

      - name: user role
        run: echo "Role of the user"

      - name: user experience
        run: echo "user experience"

      - name: user learning
        run: echo "user learning = true"

  tools:
      runs-on: ubuntu-latest

      steps:
        - name: ("GIT" , "Jenkins" , "GitLab")
          run: echo "show the tools of the user"

  hobbies:
      runs-on: ubuntu-latest

      steps:
         - name: ("drawing","playing","reading")
           run: echo "users hobbies"
        
